guilded:
  token: ""
  prefix: "/m "
  admins: []

# All asset URLs
# NOTE: If you don't have replacements for these values then please don't change them
assets:
  malLogo: "https://raw.githubusercontent.com/NotAussie/Meteor/main/assets/mal.png"

mongodb:
  # The URI to use when connecting
  uri: ""

  # The database to use when storing data
  database: "Meteor"