guilded:
  # Your Guilded.gg bot token
  token: "[ Your Guilded.gg bot token ]"

  # Command prefixes
  prefixes: [
    "/m ",      # Use "/m" or "/meteor" to invoke commands
    "/meteor ",
  ]

  # Admins (Guilded.gg account IDs)
  admins:
    - "[ Your Guilded.gg account ID ]"

igdb:
  # Your Twitch.tv application secret
  secret: "[ Your Twitch.tv application secret ]"

  # Your Twitch.tv application ID
  id: "[ Your Twitch.tv application ID ]"

mongodb:
  # Your MongoDB server URI
  uri: "[ Your MongoDB server URI ]"

  # Database name
  database: "Meteor"
